const char *doc_tmp= {
"\n"
"/**\n"
" * The input parameters. Given an input argument arg \n"
" * The fields of the input arguments can be accessed as follows :\n"
" * size(arg)   : an array of integers representing the dimensions \n"
" * ndims(arg)  : the number of dimensions  \n"
" * nrows(arg)  : the number of rows \n"
" * ncols(arg)  : the number of columns\n"
" * numel(arg)  : the number of the elements \n"
" * class(arg)  : the type of the matrix object \n"
" *\n"
" * for cell arrays, similar macros can be used to manipulate  	\n"
" * the fields. \n"
" * celldata(arg) : a pointer to the data field of the cell array arg.\n"
" * similarly:\n"
" *  celldims, cellndims, cellnrows, cellncols, cellnelem, cellcalss \n"
" **/\n"
"\n"
"\0"};
