const char *doc_ad_tmp= {
"\n"
"/**\n"
" * Macros to handle derivative objects of Type DERIV_TYPE:\n"
" *\n"
" * 	deriv(X,Y) : set a DERIV_TYPE objects whose values are X\n"
" *                   and gradients are Y \n"
" *                   DERIV_val(deriv(X,Y)) = X\n"
" * 		     DERIV_grad(deriv(X,Y)) = Y \n"
" *	grad(X)    : refers to the corresponding DERIV_TYPE object\n"
" *                   of the parameter X. 	\n"
" *                   if X is an active variable then\n"
" *                   grad(X) = deriv(X,Y) \n"
" * \n"
" * Some useful routines when dealing with adic:\n"
" * 	DERIV_TYPE* set_deriv_type(MatObj x, MatObj g_x): \n"
" *         set the values and the derivative of a matrix objects.\n"
" *      get_val(DERIV_TYPE* x,int nx, double *val): \n"
" *	   get the values of an array of DERIV_TYPE into an array \n"
" *         of double \n"
" *      get_grad(DERIV_TYPE* x,int nx, int ngrad, double *grad)\n"
" *         get the gradients of an array of DERIV_TYPE and store \n"
" *	   them into an array (ADiMAT format)   \n"
" *             \n"
" **/\n"
"\n"
"\0"};
